<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c104d40b-6f5c-473e-b3c7-e680da52f0b3</testSuiteGuid>
   <testCaseLink>
      <guid>0c6eeb7d-6823-4126-9afc-bf0c908fc10a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web API Tests/Advance Tests/DO NOT RUN/api-2-issue/Get issue/Get issue with Key</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0924e3f1-4dd6-4fa2-9cb8-20dd53193a66</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb0f8214-1d5e-41e1-a6ed-0e4908c3b304</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web API Tests/Advance Tests/EXECUTABLE/api-2-issue-tests/Scenario - Get issue information successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9df3ea07-7015-4f60-a53e-e78509f348fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d036061d-bb5c-4151-a56e-34ab51c5660b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f6eb841-ccb3-4e0d-8cd6-01405f134c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>835dfc40-853c-45c8-b2b4-c5d1020c54a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc9884df-ac77-4823-993f-a07fa50e4e02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87182904-55bf-43a6-aee0-617ff5749c32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9534e25f-a160-46bb-86ed-8acf30825f3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web API Tests/Common/The Jira System is available</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9adcba25-ca71-4685-866a-0f6274793a45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web API Tests/Simple Tests/Verify an issue information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73deec43-d316-47a6-ad55-056fd3292f4b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0dacce8-0b61-4400-8851-eee7032be2b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web UI Tests/Simple Tests/Create Issue Test/Test step with custom keyword/Create Issue with specified information</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f6a8c3a3-ac75-4ca2-bc58-e526ea12f266</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web UI Tests/Simple Tests/Login Test/Test steps which calls from other test cases/Login successfully with username and password</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a2c80f67-e905-4354-bf37-0ea037a2fb8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web UI Tests/Simple Tests/Login Test/Test data from GlobalVariable examples/Login with username and encrypted password specified in GlobalVariable</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d3123e15-091b-41a5-b69b-7570aa304a30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web UI Tests/Simple Tests/Login Test/Test data from GlobalVariable examples/Login with username and password specified in GlobalVariable</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>26f979eb-b249-470e-b9ce-48b7e01b3cbf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web UI Tests/Simple Tests/Login Test/Test data hardcoding examples/Login with username and password specified in the test steps</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d54b0413-e62d-4cd1-a5c0-d2c685abea5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web UI Tests/Simple Tests/Login Test/Data-driven examples/Login with username and password as a default value of variables</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a11316c-738f-4e70-a8b5-63aaf81e1d91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deb3cf4c-1dee-42c6-ab83-fae4778b5936</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cc03798-e42e-46f2-80c5-e66dff23ac09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web UI Tests/Simple Tests/Login Test/Data-driven examples/Login with username and password as variables passed by data-files</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>11cc210d-b2e7-4c9c-a8af-df8eed10cd6a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/valid-accounts</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>11cc210d-b2e7-4c9c-a8af-df8eed10cd6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>fdde4842-9fe3-4fb6-9c10-485c3a78a9dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>11cc210d-b2e7-4c9c-a8af-df8eed10cd6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>7934176c-9dd2-4059-9914-100665990135</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6b5850f-642e-4bff-9cd5-e7b77b900a82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web UI Tests/Start Web UI Testing</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
