<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Data driven tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0c071e44-c30c-46a8-9063-e68816294632</testSuiteGuid>
   <testCaseLink>
      <guid>cccf5cef-f91a-49b6-a033-832aa5ec9788</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web API Tests/Advance Tests/EXECUTABLE/api-2-issue-tests/Scenario - Get issue information successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9df3ea07-7015-4f60-a53e-e78509f348fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d036061d-bb5c-4151-a56e-34ab51c5660b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f6eb841-ccb3-4e0d-8cd6-01405f134c61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>835dfc40-853c-45c8-b2b4-c5d1020c54a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc9884df-ac77-4823-993f-a07fa50e4e02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87182904-55bf-43a6-aee0-617ff5749c32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>443ea0ab-3df4-4330-8aad-d0055375d28e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web API Tests/Advance Tests/DO NOT RUN/api-2-issue/Create issue/I call Create issue API to create a new ticket with specified information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08ae52e0-dd08-4b98-8366-f19eedf7f083</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c0dac33-99a9-4e77-9498-4788bde6a03e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88e4e8ea-8592-45b6-969a-613e77ff5e93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ff032f1-4e72-4eb3-aee0-9551d4c156cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69350ebf-5de8-4dcf-a481-5213bfc8de85</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0beaecc-5a9c-48cb-8f30-8770ce56d194</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web API Tests/Simple Tests/Verify an issue information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73deec43-d316-47a6-ad55-056fd3292f4b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
